### ISSUE TITLE
Find a way to incorporate capital letters into phrase

### ISSUE THREAD

**Issue by philipmw** [philipmw/phrase.shop#38]
Capital letters are required for many passphrases, but phrase.shop's attitude toward that is, "just capitalize it yourself." But maybe customers want a capitalized phrase delivered?

Some options are to randomly capitalize the start of each word, to randomly capitalize the first word, or even randomly capitalize any letter.

**Comment by robbielove** [comment]
Hey @philipmw,

I think you could add an option that randomly capitalizes any letter in the phrase as a checkbox feature on the phrase input page. Alternatively, you could make it so that the start of each word is always capitalized. Let me know what you think!

Security vs memorability

Users might have a hard time remembering a phrase that has randomly capitalized letters, since it would be less predictable. For example, if the phrase "this is a phrase" was randomly capitalized, it could become "ThIs iS A phRaSe." This would make it more difficult for users to remember, since they would have to learn the new pattern of capitalization.

If you always capitalize the start of each word, the phrase would be more predictable and thus less secure. For example, the phrase "this is a phrase" would become "This Is A Phrase." This would make it easier for someone to guess the phrase since they would know which letters are capitalized.

One compromise might be to randomly capitalize the first letter of each word. This would make the phrase more predictable and thus easier to remember, but it would still be more secure than always capitalizing the start of each word. For example, the phrase "the brown fox jumped over the lazy dog" could become "The brown Fox jumped over the lazy Dog."

What do you think?

**Comment by philipmw** [comment]
I agree with randomly capitalizing the first letter of words. I implemented it!

Thanks for the feedback.
