### ISSUE TITLE
Ability to type dice values

### ISSUE THREAD

**Issue by robbielove** [philipmw/phrase.shop#41]
It can become tedious to manually enter each dice value with a click on a button. 
Especially when those first 6 dice have icons that are very hard to see without squinting.

Please add a text entry box that allows multiple dice values to be entered at once using a space or comma etc, to separate the values.

This way a user can throw multiple dice and type the values instead of matching them to values on a screen that need to be clicked (it's more optimized to enter them on a keyboard where the user may already know the positions of the keys such as the Numpad)

Additionally, they could potentially copy and paste the values from a premade CSV string of their dice results - making it much faster to enter dice rolls as opposed to generated ones (making it less likely a user will choose the generated option for convenience reasons - which is less secure)

**Comment by philipmw** [comment]
Hi.

I am not sure about the text entry box because this would add complexity to the UI (as I'd still want to retain buttons for users who don't want to type), and it would add new failure modes. The app would need to validate input, show error messages, etc.

Would it solve your problem if we make the existing buttons larger?
